#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// ESP32-S31-Korvo-1 — 对齐小智官方板级 + MetalioClaw4 扩展宏
// 参考：https://github.com/78/xiaozhi-esp32/tree/main/main/boards/espressif/esp32-s31-korvo-1

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

// ES8389 + 双 NS4150B（官方 esp-bsp esp32_s31_korvo_1）
// MCLK 脚存在但未接到 codec，必须 use_mclk=false
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_2
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_3
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_5

#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_0
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_1
#define I2C_SDA_PIN AUDIO_CODEC_I2C_SDA_PIN
#define I2C_SCL_PIN AUDIO_CODEC_I2C_SCL_PIN
#define AUDIO_CODEC_PA_PIN      GPIO_NUM_7
#define AUDIO_CODEC_ES8389_ADDR 0x20  // ES8389_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_USE_MCLK    false

// 本板使用片上蓝牙，无外置 AT 模块
#define BOARD_HAS_EXTERNAL_BT 0
#define BOARD_HAS_NATIVE_BT 1
#define BT_AUDIO_TX_PIN GPIO_NUM_NC
#define BT_AUDIO_RX_PIN GPIO_NUM_NC

#define BUILTIN_LED_GPIO GPIO_NUM_37
#define BOOT_BUTTON_GPIO GPIO_NUM_61
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC
#define POWER_BUTTON_PIN        GPIO_NUM_NC

// ADC 按键（SET/MODE/VOL-/VOL+）GPIO42
#define ADC_BUTTON_GPIO GPIO_NUM_42
#define ADC_BUTTON_SET_MV      1870
#define ADC_BUTTON_MODE_MV     1340
#define ADC_BUTTON_VOL_DOWN_MV 820
#define ADC_BUTTON_VOL_UP_MV   380
#define ADC_BUTTON_IDLE_MV     2000

// RGB 800x480（ST7262E43），背光常开
#define DISPLAY_WIDTH   800
#define DISPLAY_HEIGHT  480
#define DISPLAY_MIRROR_X  false
#define DISPLAY_MIRROR_Y  false
#define DISPLAY_SWAP_XY   false
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define BOARD_DISPLAY_RGB 1

#define LCD_RGB_VSYNC GPIO_NUM_45
#define LCD_RGB_HSYNC GPIO_NUM_44
#define LCD_RGB_DE    GPIO_NUM_43
#define LCD_RGB_PCLK  GPIO_NUM_40
#define LCD_RGB_DISP  GPIO_NUM_38
#define LCD_RGB_DATA0  GPIO_NUM_8
#define LCD_RGB_DATA1  GPIO_NUM_9
#define LCD_RGB_DATA2  GPIO_NUM_10
#define LCD_RGB_DATA3  GPIO_NUM_11
#define LCD_RGB_DATA4  GPIO_NUM_12
#define LCD_RGB_DATA5  GPIO_NUM_13
#define LCD_RGB_DATA6  GPIO_NUM_14
#define LCD_RGB_DATA7  GPIO_NUM_15
#define LCD_RGB_DATA8  GPIO_NUM_16
#define LCD_RGB_DATA9  GPIO_NUM_17
#define LCD_RGB_DATA10 GPIO_NUM_18
#define LCD_RGB_DATA11 GPIO_NUM_19
#define LCD_RGB_DATA12 GPIO_NUM_33
#define LCD_RGB_DATA13 GPIO_NUM_34
#define LCD_RGB_DATA14 GPIO_NUM_35
#define LCD_RGB_DATA15 GPIO_NUM_36

// OV3660 DVP（SCCB 与 codec 共享 I2C）
#define CAMERA_PIN_XCLK  GPIO_NUM_55
#define CAMERA_PIN_PCLK  GPIO_NUM_54
#define CAMERA_PIN_VSYNC GPIO_NUM_56
#define CAMERA_PIN_HREF  GPIO_NUM_57
#define CAMERA_PIN_D0    GPIO_NUM_46
#define CAMERA_PIN_D1    GPIO_NUM_47
#define CAMERA_PIN_D2    GPIO_NUM_48
#define CAMERA_PIN_D3    GPIO_NUM_49
#define CAMERA_PIN_D4    GPIO_NUM_50
#define CAMERA_PIN_D5    GPIO_NUM_51
#define CAMERA_PIN_D6    GPIO_NUM_52
#define CAMERA_PIN_D7    GPIO_NUM_53
#define CAMERA_PIN_RESET GPIO_NUM_NC
#define CAMERA_PIN_PWDN  GPIO_NUM_NC
#define CAMERA_XCLK_FREQ_HZ  (20 * 1000 * 1000)
#define CAMERA_SCCB_FREQ_HZ  (10 * 1000)
#define CAMERA_VFLIP   true
#define CAMERA_HMIRROR true

// SDMMC 4-bit；电源使能低有效（无 P4 片上 LDO）
#define SDMMC_CLK_PIN GPIO_NUM_24
#define SDMMC_CMD_PIN GPIO_NUM_25
#define SDMMC_D0_PIN  GPIO_NUM_20
#define SDMMC_D1_PIN  GPIO_NUM_21
#define SDMMC_D2_PIN  GPIO_NUM_22
#define SDMMC_D3_PIN  GPIO_NUM_23
#define SDMMC_PWR_EN_PIN GPIO_NUM_39
#define SDMMC_PWR_EN_ACTIVE_LEVEL 0

#endif  // _BOARD_CONFIG_H_
