#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/spi_master.h>
#include <driver/uart.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_INPUT_REFERENCE    true

#define PG1_POWER_KEY_GPIO          GPIO_NUM_16
#define PG1_POWER_KEY_ACTIVE_LEVEL  0
#define PG2_HOLD_GPIO               GPIO_NUM_7
#define PG2_HOLD_ACTIVE_LEVEL       1

#define KEY_SW1_LONG_PRESS_MS 500
#define KEY_GPIO_POLL_MS      100

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_42
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_39
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_40
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_38
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_41

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_4
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_2
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_1
#define I2C_SDA_PIN              AUDIO_CODEC_I2C_SDA_PIN
#define I2C_SCL_PIN              AUDIO_CODEC_I2C_SCL_PIN
#define AUDIO_CODEC_ES8311_ADDR  0x30
#define AUDIO_CODEC_ES7210_ADDR  0x80

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define DISPLAY_WIDTH    360
#define DISPLAY_HEIGHT   360
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY  false
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define QSPI_LCD_H_RES         360
#define QSPI_LCD_V_RES         360
#define QSPI_LCD_BIT_PER_PIXEL 16
#define QSPI_LCD_HOST          SPI2_HOST
#define QSPI_PIN_NUM_LCD_PCLK  GPIO_NUM_14
#define QSPI_PIN_NUM_LCD_CS    GPIO_NUM_10
#define QSPI_PIN_NUM_LCD_DATA0 GPIO_NUM_13
#define QSPI_PIN_NUM_LCD_DATA1 GPIO_NUM_9
#define QSPI_PIN_NUM_LCD_DATA2 GPIO_NUM_12
#define QSPI_PIN_NUM_LCD_DATA3 GPIO_NUM_46
#define QSPI_PIN_NUM_LCD_RST   GPIO_NUM_21
#define QSPI_PIN_NUM_LCD_TE    GPIO_NUM_17
#define QSPI_PIN_NUM_LCD_BL    GPIO_NUM_3

#define DISPLAY_BACKLIGHT_PIN           QSPI_PIN_NUM_LCD_BL
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define TP_PORT        I2C_NUM_0
#define TP_PIN_NUM_RST GPIO_NUM_NC
#define TP_PIN_NUM_INT GPIO_NUM_11

#define BSP_SD_CLK GPIO_NUM_48
#define BSP_SD_CMD GPIO_NUM_45
#define BSP_SD_D0  GPIO_NUM_47
#define SDMMC_CLK_PIN   BSP_SD_CLK
#define SDMMC_CMD_PIN   BSP_SD_CMD
#define SDMMC_D0_PIN    BSP_SD_D0
#define SDMMC_D1_PIN    GPIO_NUM_NC
#define SDMMC_D2_PIN    GPIO_NUM_NC
#define SDMMC_D3_PIN    GPIO_NUM_NC
#define SDMMC_BUS_WIDTH 1
#define MOUNT_POINT "/sdcard"

#define ML307_RX_PIN   GPIO_NUM_5
#define ML307_TX_PIN   GPIO_NUM_6
#define ML307_UART_NUM UART_NUM_2
#define ML307_EN_PIN   GPIO_NUM_15

#define UART1_TX GPIO_NUM_43
#define UART1_RX GPIO_NUM_44

#define TOUCH_PAD2 GPIO_NUM_8
#define TOUCH_PAD1 GPIO_NUM_NC
#define HEAD_TOUCH_GPIO         TOUCH_PAD2
#define HEAD_TOUCH_ACTIVE_LEVEL 1

#define SPEAKING_LED_GPIO         GPIO_NUM_18
#define SPEAKING_LED_ACTIVE_LEVEL 0

#define VIBRATE_MOTOR_GPIO GPIO_NUM_NC

#define BOARD_HAS_EXTERNAL_BT 0
#define BOARD_HAS_NATIVE_BT   0
#define BT_AUDIO_TX_PIN       GPIO_NUM_NC
#define BT_AUDIO_RX_PIN       GPIO_NUM_NC

#define BOARD_ESP_VOCAT 1

#endif  // _BOARD_CONFIG_H_
